### PR TITLE
Prevents error message render for empty values

### PR DESCRIPTION
**Pull request by Chrischuck**
fix issue #780 

## Before
Screen Shot 2020-04-16 at 18 02 29

## After
Screen Shot 2020-04-16 at 18 04 09

### CODE REVIEW

**Comment by akleiner2** [comment]
Seems sane to me! My only comment is that `renderX` methods are a usually code smell to move `X` into its own component, but non-blocking :)

**Comment by Chrischuck** [comment]
> Seems sane to me! My only comment is that `renderX` methods are a usually code smell to move `X` into its own component, but non-blocking :)

Hmm, fair point, in that case do you think  `FormFieldValidationMessage` should handle returning `null` if it's an empty string? I'm kind of leaning towards that idea actually since that would mean `FormFieldValidationMessage` handles all string types

**Comment by jibberishclient** [comment]
Is there any update on this? Additionally I think there should be other composed form fields for selects, radios, and text areas just as there is for TextFieldInput such that it will make it easier for form libraries like formik and redux-form, etc. instead of having to destructure props to both the input itself and the wrapping form field.

Secondly on that note, I think the visibility of the validationMessage should rely entirely on isValid. In terms of UX, you're only going to want to show an error message if the input is also styled with a danger/warning intent. Thus it makes sense to have validationMessage render conditionally based on isValid regardless of its value such that the both of them are "in sync"

**Comment by mshwery** [comment]
> Hmm, fair point, in that case do you think `FormFieldValidationMessage` should handle returning `null` if it's an empty string? I'm kind of leaning towards that idea actually since that would mean `FormFieldValidationMessage` handles all string types

I think that'd be fine as long as we can guarantee that having that component will never add an empty styled div. We also want to make sure it's obvious to wherever the component is used.

**Comment by jibberishclient** [comment]
Will this be available in yarn? Or do we have to wait until a new release?

**Pull request closed without merging**
