### PR TITLE
Check if invalid aria is true rather than present

### LINKED ISSUE #464: SelectField isInvalid not treated as boolean
The `<SelectField />` component has a property `isInvalid`, which should be treated as a boolean (as with the `<TextInputField />` component).

It seems the component is checking for presence of the property, rather than it's value.

## What I did

Set `isInvalid={false}` on the `<SelectField />` component:

```jsx
<SelectField
  isInvalid={false}
  required
  label="A required text input field"
  description="This is a description."
>
  <option value="foo" checked>Foo</option>
  <option value="bar">Bar</option>
</SelectField>
```

## What I expected to happen

The component to render with a _valid_ state (and no red border) - just like the `<TextInputField />` component.

## What happened

The component rendered with the _invalid_ state. From your live docs:

screenshot 2018-12-07 16 28 29

## Workaround

Remove `isInvalid` entirely so the field renders as expected.

---

Thanks for the awesome component library 🙌

### PR DESCRIPTION
**Pull request by dillonhafer**
Fixes #464

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Could you also modify https://github.com/segmentio/evergreen/blob/master/src/select/src/Select.js#L136 to be `aria-invalid={String(isInvalid)}`?

**Comment by vadimdemedes** [comment]
This will also involve adding a default `false` value for `isInvalid` prop.

**Comment by dillonhafer** [comment]
Sure thing!

**Comment by vadimdemedes** [comment]
Thanks!

**Pull request merged**
