### PR TITLE
Runtime warnings

### PR DESCRIPTION
**Pull request by vadimdemedes**
This PR starts an initiative to introduce runtime warnings in development to help developers notice and fix common mistakes. Being an active user of Evergreen, I still use onClick prop instead of onSelect sometimes. After this is merged, this is what I would see if I did it again:

cleanshot 2018-10-31 at 21 24 36 2x

Happy to tweak error messages, if needed.

### CODE REVIEW

**Comment by vadimdemedes** [comment]
> Is there a way to flag this for removal from most bundlers?
It will be auto removed on minify step. It's the same way warnings are shown in React, Redux, etc.

> I don't know that the extra package is worth these warnings.
This package weighs 130 bytes after minification.

> I think the typeof checking is good enough.
`warning` doens't check anything, it's responsible only for showing warnings and ensuring there's only one warning shown per session.

**Comment by jeroenransijn** [comment]
@vadimdemedes as a fyi, @Rowno did this in `ui-box` https://github.com/segmentio/ui-box/blob/756f9f915bb89cfb8c0805200249ad63f9f0ea00/src/box.js#L35

Not sure what tradeoffs would be

**Comment by vadimdemedes** [comment]
What tradeoffs do you mean? I don't follow.

**Comment by mshwery** [comment]
LGTM then

**Pull request merged**
