### PR TITLE
add focus feedback to segmented controls

### PR DESCRIPTION
**Pull request by bmcmahen**
I needed focus feedback in segmented controls for accessibility purposes... so here's my quick solution. Just noticed that this should address #229.

### CODE REVIEW

**Comment by jeroenransijn** [comment]
Awesome @bmcmahen! Could you provide a gif or screenshot of the result?

**Comment by bmcmahen** [comment]
here ya go

segmented-controls-focus

I think this is the proper behaviour for accessibility. When working through a form using tabs it focuses on the selected radio button initially. Left - right keys shift both focus and radio selection. And the selected state remains when focus shift to somewhere else on the page. The actual shadow used already existed in your code.

**Comment by jeroenransijn** [comment]
I will have to move this in v4 as well!

**Comment by jeroenransijn** [comment]
`evergreen-ui 3.2.5 published`

**Pull request merged**
