### PR TITLE
Text input field icon

### PR DESCRIPTION
**Pull request by edumoreira1506**
Issue #521 

Before:
The text input field was simple and did not have icon.

Now:
The text input field can have a icon and set the position, like right or left and how many pixels far from the edge.

Have some examples on storybook.

### CODE REVIEW

**Comment by edumoreira1506** [comment]
Sure! Here have some examples.
Screenshot from 2019-09-11 15-53-13

**Comment by mshwery** [comment]
@edumoreira1506 what happens when you click on the icon? Does it focus the input? Does it bubble the same events?

I'm wondering if it makes more sense to push the icon behavior into the `TextInput` instead?

**Comment by edumoreira1506** [comment]
This PR just add the icon on text input field. When you click on the icon nothing happensg, like any other input with icon, for just the icon help to describe what the input need. Like the example:

Screenshot from 2019-10-24 13-49-21

**Comment by mshwery** [comment]
IMO since it looks like it is _inside_ the input box, it should trigger focus on the input. That is to say, we should probably move this into the `TextInput` component so we get this behavior for free.

**Pull request closed without merging**
