### PR TITLE
Support value prop for Switch component

### PR DESCRIPTION
**Pull request by prateekgoel**
This pull request targets https://github.com/segmentio/evergreen/issues/325.
I have added support for value prop.
I am new contributing to this repository. Please suggest any improvements and I would be happy to do the changes.

### CODE REVIEW

**Comment by Flaque** [comment]
> Relaying @jeroenransijn's comments in here:

The switch is semantically a checkbox, I think it should be the `checked` prop instead of `value`. https://evergreen.segment.com/components/switch

```javascript
<Switch onChange={this.handleChange} checked={isChecked} value="some value" />
```

The `value` prop is pretty much only useful in non-ajax traditional form submissions.

To give a bit more context you can read about checkboxes here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

We should optimize for passing the `event` into the `onChange` handler.

**Comment by prateekgoel** [comment]
@Flaque I added one commit. Did you intend this?

**Comment by jeroenransijn** [comment]
@prateekgoel we should pass the `event` (e) itself to the `onChange` handler. 

```javascript
handleChange = e => {
    if (isControlled(this)) {
      this.props.onChange(e)
    } else {
      this.setState(({ checked }) => ({
        checked: !checked
      }))
      this.props.onChange(e)
    }
  }
```

**Comment by prateekgoel** [comment]
Got it. I will do the changes. Thanks.

**Pull request closed without merging**
