### PR TITLE
Fixes keyup/keydown/enter in select-menu component

### LINKED ISSUE #201: Select Menu Selection + Filtering bug
select menu filtering selection

### PR DESCRIPTION
**Pull request by jssridhar**
Fixes #201.

Please let me know if this fix makes sense. I am slightly confused as to what the expected behaviour should be in case of multi select.

### CODE REVIEW

**Comment by jeroenransijn** [comment]
Hey @jssridhar thanks so much for taking the time and put in this PR 👍  — much appreciated!
Select menu, dropdowns, they are super confusing to get right in terms of functionality and accessibility. It will take some time for us to get it perfectly right.

It looks good from just eyeballing the code. Could you provide a gif of the behavior? Here is a tool to do that if you don't have one: https://getkap.co/

A gif would be appreciated, if you show that, I would say let's merge it in!

**Comment by jssridhar** [comment]
True that! I am still looking at ways to get this fixed in the multi-select component, will submit another pr for it if I can get it working.
functionality gif
selectmenu

**Comment by jeroenransijn** [comment]
@jssridhar thanks for sharing the gif! Long term, we might want to consider using the arrow keys to focus an item, but use enter to select/deselect an item. I am working on an implementation in v4 that uses this approach and it works pretty well.

> True that! I am still looking at ways to get this fixed in the multi-select component, will submit another pr for it if I can get it working.

Is this PR ready to merge?

**Comment by jssridhar** [comment]
Yep, this is ready for merge!

**Comment by jeroenransijn** [comment]
🎉  Published in `v3.2.4`: 
 https://circleci.com/gh/segmentio/evergreen/538

**Pull request merged**
