### PR TITLE
Adds Chromatic regression tests

### PR DESCRIPTION
**Pull request by zol**
Hi,

I’m one of the founders at [Chromatic](http://chromaticqa.com), a visual regression testing tool. We’ve been using Evergreen as a test case for Chromatic itself (we really like your design aesthetic too).  

As a token of our appreciation, I’d like to offer the Evergreen team Chromatic for free. We’ll also give you hands on support to make sure you have a smooth ride and can get the most out of the tool without taking up much of your time. I've made a small PR that adds visual regression tests. 

Chromatic will quickly and easily let you review any visual changes introduced by new code -- it’s especially handy for open source projects where it can be time consuming to evaluate PRs being opened out of the blue by unknown authors.

I’ve already run Chromatic on Evergreen to establish a baseline for future tests (you can view the results [here](https://www.chromaticqa.com/builds?appId=5a85f7d31341780020097a7a)). You can run additional tests anytime by calling `npm chromatic`. You could try running `npm chromatic` in this branch after changing a component to see an example of the review flow.

Chromatic really shines when you run the above command from within your CI system as it will then tag PRs with the result of the regression tests, like in the image below.

screen shot 2018-02-23 at 4 42 52 pm

Let me know if you have any questions, once this PR is merged I can help get chromatic running in your CI builds too if you'd like.

### CODE REVIEW

**Comment by jeroenransijn** [comment]
Very cool! Thanks for taking the time and offering this to us and this project. I would love to learn more and how we can incorporate this in our product.

Quick question, what OS is doing the rendering of the screens. Since we default to system fonts it seems to be using something other than SF. I think it's the Ubuntu/Linux default system font?

**Comment by zol** [comment]
Our pleasure!! One thing we've noticed is that the server serving up the cat images sometimes fails likely due to the high number of our parallel renderers hitting it over a short time period. This combined with the inherent randomness of the cat images triggers changes in Chromatic. If you're open to it we can do a quick refactor to make these consistent.

You're correct in that we're currently using Linux system fonts with headless Chrome. 

Currently, the focus is to detect regressions as well as showing a close approximation of what the rendered component will look like (approximation because a target user could be on any number of platforms). We'll be adding more renderers in the near future which will open up the door to high fidelity multi platform previews.

**Comment by jeroenransijn** [comment]
@zol thanks for the fast response. Yeah feel free to make changes to the cat image :)

**Comment by jeroenransijn** [comment]
@zol what is the status of this? Should we update the branch from master?

**Comment by zol** [comment]
@jeroenransijn I was literally just looking at it and it seems like the cat images are no longer causing any randomness so we should be good to go on merging it. I'll keep an eye on the builds and open a PR  if I notice anything.

**Comment by zol** [comment]
Hey @jeroenransijn, can I help do something to get this merged? I know it can be annoying to have PRs lying around. If there are any blockers, let me know!

**Comment by jeroenransijn** [comment]
@zol whoops, mainly just forgot about this PR — getting it in now :)

**Comment by zol** [comment]
Sweet!

**Pull request merged**
