### PR TITLE
[V6]docs(colors): support v6 (obj / string)

### PR DESCRIPTION
**Pull request by wangcch**
**Overview**

**Screenshots (if applicable)**
localhost_6006__path=_story_colors--overview(720p)

**Documentation**
- [ ] Updated Typescript types and/or component PropTypes
- [ ] Added / modified component docs
- [x] Added / modified Storybook stories

### CODE REVIEW

**Comment by akleiner2** [comment]
Awesome! Thanks for the PR - the code looks good :). Just need to see why Chromatic is failing.

**Comment by wangcch** [comment]
> Awesome! Thanks for the PR - the code looks good :). Just need to see why Chromatic is failing.

https://github.com/segmentio/evergreen/pull/1057/files#diff-007fd58da9f3a8b4577829dd6415143aL38
The type of `theme.colors[key]` is string or object in v6.
But [`ColorGroup.colorGroup`](https://github.com/segmentio/evergreen/blob/v6/src/colors/stories/ColorGroup.js#L14) needs object.

**Comment by wangcch** [comment]
> Awesome! Thanks for the PR - the code looks good :). Just need to see why Chromatic is failing.

'Missing project token' ?

**Comment by wangcch** [comment]
Hi @akleiner2 

> ✖ Missing project token

I think I don’t have permission for `chromatic-segmentio/evergreen`.
My fork repository can run. https://www.chromatic.com/build?appId=5f703094dcc2ce00224b62bd&number=1

**Comment by mshwery** [comment]
Weird. We havent encountered this issue with any other PRs from contributors yet, afaik.

**Comment by wangcch** [comment]
> Weird. We havent encountered this issue with any other PRs from contributors yet, afaik.

Thanks for you reply. Is it V6?

🙆‍♂️

localhost_6006__path=_story_colors--overview(720p) (1)

**Comment by mshwery** [comment]
> Weird. We havent encountered this issue with any other PRs from contributors yet, afaik.

Let me clarify this ☝️. I meant to say we haven't encountered the `'Missing project token'` error with other PRs from contributors as far as I can tell, but I might be missing something.

**Comment by colinlohner** [comment]
Did something similar, and resolved storybook error in this PR: https://github.com/segmentio/evergreen/pull/1070

Closing this one in favor

**Pull request closed without merging**
