### PR TITLE
<Dialog>: Add "press enter to submit" form behavior

### PR DESCRIPTION
**Pull request by nucleartide**
_Note that this pull request is a work-in-progress._

This pull request adds a "press enter to submit" form behavior to Evergreen's `<Dialog>` component.

### CODE REVIEW

**Comment by nucleartide** [comment]
Closing this, won't address this at the moment.

**Comment by karltaylor** [comment]
I'm actually having a different issue with this at the moment.

If I have the following Dialog component, the form will not submit, however if there is only 1 TextInputField, the form will submit. Any ideas?

```
<Dialog>
  <form>
    <TextInputField />
    <TextInputField />
  </form>
</Dialog>

**Comment by mshwery** [comment]
I believe this is standard html form behavior. It's part of the [html spec](https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2):

>When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.

**Comment by mshwery** [comment]
As a workaround you can add event handlers or you can try adding a submit button/input to the form.

**Comment by karltaylor** [comment]
> I believe this is standard html form behavior. It's part of the [html spec](https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2):
> 
> > When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.

Well shit, I've learnt something new today. Thanks @mshwery!

**Pull request closed without merging**
