### PR TITLE
Add disabled tabs support

### PR DESCRIPTION
**Pull request by prateekgoel**
Related to issue #174

### CODE REVIEW

**Comment by prateekgoel** [comment]
@jeroenransijn After my last changes, the styles are not matching with the last snapshot. Can you please help me with this?

**Comment by prateekgoel** [comment]
@jeroenransijn Any update on this?

**Comment by jeroenransijn** [comment]
@prateekgoel hi sorry for my late reply! This is looking good so far. To update the snapshots run `ava -u`. You might need to globally install [ava](https://github.com/avajs/ava).

**Comment by prateekgoel** [comment]
@jeroenransijn It's all right. Thank you for the response. :)
All checks are passing now.

**Comment by jeroenransijn** [comment]
https://github.com/segmentio/evergreen/releases/tag/v4.4.0

**Pull request merged**
